
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fr' | 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.settings': 'Paramètres',
    'nav.planner': 'Mon Plan',
    'nav.logout': 'Déconnexion',
    'nav.menu': 'Menu Principal',
    'dash.welcome': 'Bienvenue, Maman',
    'dash.welcome_badge': 'Bienvenue dans votre voyage',
    'dash.subtitle': 'Tout ce dont vous avez besoin pour une diversification alimentaire sereine, nutritive et pleine d\'amour.',
    'dash.modules': 'Modules',
    'dash.bonus': 'Bonus Exclusifs',
    'dash.recommended': 'Sélectionnés pour vous',
    'dash.feedback.title': 'Vous aimez NutriBebe ?',
    'dash.feedback.text': 'Votre avis est précieux ! Si vous avez des suggestions, des questions ou si vous souhaitez simplement nous dire à quel point vous appréciez l\'appli, nous sommes à votre écoute.',
    'dash.feedback.button': 'Contacter le Support',
    'dash.app_mobile': 'App NutriBebe',
    'planner.title': 'Menu de la Semaine',
    'planner.subtitle': 'Un guide personnalisé selon l\'âge et les besoins de votre bébé.',
    'planner.setup': 'Profil du Bébé',
    'planner.edit': 'Modifier le profil',
    'planner.cancel': 'Annuler',
    'planner.babyName': 'Comment s\'appelle votre petit trésor ?',
    'planner.name_placeholder': 'Nom du bébé',
    'planner.birthDate': 'Sa date de naissance',
    'planner.method': 'Méthode choisie',
    'planner.method.blw': 'DME (Morceaux)',
    'planner.method.traditional': 'Classique (Purées)',
    'planner.method.mixed': 'Mixte',
    'planner.restrictions': 'Allergies ou aversions',
    'planner.save': 'Enregistrer le profil',
    'planner.generate': 'Générer une nouvelle semaine',
    'planner.generate.desc': 'Voulez-vous changer les repas de cette semaine ? Créons un nouveau menu de 7 jours 💛',
    'planner.menu.week': 'Menu de 7 Jours',
    'planner.shopping': 'Liste de Courses',
    'planner.day': 'Jour',
    'planner.motivation': 'Chaque bouchée est une nouvelle découverte. Vous faites un travail merveilleux ! 💛',
    'planner.disclaimer': 'Important : Ce plan est un guide nutritionnel et ne remplace pas les conseils personnalisés de votre pédiatre.',
    'planner.empty': 'Veuillez configurer le profil pour voir le menu.',
    'planner.age.month': 'mois',
    'planner.age.months': 'mois',
    'planner.milk.title': 'Toujours au lait !',
    'planner.milk.desc': 'Votre bébé a {age} mois. L\'OMS recommande l\'allaitement exclusif jusqu\'à 6 mois. Revenez à ses 6 mois ! 💛',
    'settings.title': 'Préférences',
    'settings.subtitle': 'Personnalisez votre expérience.',
    'settings.lang': 'Langue',
    'settings.save': 'Enregistrer',
    'settings.saved': 'Enregistré !',
    'footer.curation': 'Curateur de diversification alimentaire',
    
    'auth.login.title': 'Bon retour',
    'auth.login.subtitle': 'Connectez-vous pour continuer l\'aventure.',
    'auth.register.title': 'Créer un compte',
    'auth.register.subtitle': 'Rejoignez notre communauté de mamans.',
    'auth.email': 'Adresse Email',
    'auth.pass': 'Mot de passe',
    'auth.confirmPass': 'Confirmer le mot de passe',
    'auth.placeholder.email': 'exemple@email.com',
    'auth.enter': 'Se connecter',
    'auth.createAccount': 'S\'inscrire',
    'auth.forgotLink': 'Mot de passe oublié ?',
    'auth.noAccount': 'Pas encore de compte ?',
    'auth.registerHere': 'Inscrivez-vous ici',
    'auth.hasAccount': 'Déjà un compte ?',
    'auth.loginHere': 'Connectez-vous',
    'auth.loading.enter': 'Connexion...',
    'auth.loading.create': 'Création...',
    'auth.error.invalid': 'Identifiants invalides.',
    'auth.error.locked': 'Compte temporairement bloqué. Réessayez plus tard.',
    'auth.error.exists': 'Cet email est déjà utilisé.',
    'auth.error.ip_limit': 'Une seule inscription est autorisée par adresse IP.',
    'auth.error.match': 'Les mots de passe ne correspondent pas.',
    'auth.forgot.title': 'Récupération',
    'auth.forgot.subtitle': 'Entrez votre email pour recevoir un lien.',
    'auth.sendLink': 'Envoyer le lien',
    'auth.backLogin': 'Retour à la connexion',
    'auth.successReset': 'Lien envoyé avec succès !',
    'auth.checkInbox': 'Vérifiez votre boîte de réception.',

    'meal.lunch': 'Déjeuner', 'meal.snack': 'Goûter', 'meal.dinner': 'Dîner',
    'meal.ingredients_label': 'Aliments utilisés :',
    'meal.l1': 'Délice de Potiron au Poulet',
    'meal.l2': 'Purée Douce Boeuf et Carotte',
    'meal.l3': 'Mix de Chayote et Haricots',
    'meal.l4': 'Velouté Petits Pois et Oeuf',
    'meal.l5': 'Poisson Blanc et Courgettes',
    'meal.l6': 'Chou-fleur et Lentilles Corail',
    'meal.l7': 'Épinards et Viande Hachée',
    'meal.l8': 'Quinoa aux Légumes et Boeuf',
    'meal.l9': 'Riz au Poulet et Épinards',
    'meal.l10': 'Poisson et Pommes de Terre',
    'meal.l11': 'Omelette Douce au Maïs',
    'meal.l12': 'Saumon et Riz Complet',
    'meal.l13': 'Poulet Rôti et Légumes',
    'meal.s1': 'Papaye en Dés', 'meal.s2': 'Banane Écrasée', 'meal.s3': 'Avocat Crémeux',
    'meal.s4': 'Poire Douce', 'meal.s5': 'Mangue Fraîche', 'meal.s6': 'Pomme au Four',
    'meal.s7': 'Melon Rafraîchissant', 'meal.s8': 'Yaourt et Banane', 'meal.s9': 'Fraise et Avoine',
    'meal.s10': 'Pomme et Pain Perdu', 'meal.s11': 'Gâteau Banane Avoine',
    'meal.d1': 'Dîner Léger Potiron', 'meal.d2': 'Mélange Fruité Banane Mangue',
    'meal.d3': 'Pomme de Terre et Chou-fleur', 'meal.d4': 'Riz aux Petits Pois',
    'meal.d5': 'Soupe Courgettes Chayote', 'meal.d6': 'Lentilles aux Carottes',
    'meal.d7': 'Riz au Brocoli', 'meal.d8': 'Soupe de Lentilles', 'meal.d9': 'Pâtes Tomate Poulet',
    'meal.d10': 'Risotto aux Épinards', 'meal.d11': 'Quiche aux Poireaux',
    'ing.potiron': 'Potiron', 'ing.poulet': 'Poulet', 'ing.patateDouce': 'Patate Douce',
    'ing.carotte': 'Carotte', 'ing.riz': 'Riz', 'ing.viandeHachee': 'Viande Hachée',
    'ing.chayote': 'Chayote', 'ing.haricots': 'Haricots', 'ing.pommeDeTerre': 'Pomme de Terre',
    'ing.petitsPois': 'Petits Pois', 'ing.oeuf': 'Oeuf', 'ing.brocoli': 'Brocoli',
    'ing.abobrinha': 'Courgette', 'ing.poissonBlanc': 'Poisson Blanc', 'ing.mais': 'Maïs',
    'ing.choufleur': 'Chou-fleur', 'ing.lentilles': 'Lentilles', 'ing.epinards': 'Épinards',
    'ing.papaye': 'Papaye', 'ing.banane': 'Banane', 'ing.avocat': 'Avocat',
    'ing.pear': 'Poire', 'ing.mango': 'Mangue', 'ing.pomme': 'Pomme', 'ing.melon': 'Melon',
    'ing.boeuf': 'Boeuf', 'ing.quinoa': 'Quinoa', 'ing.yaourt': 'Yaourt', 'ing.fraise': 'Fraise',
    'ing.avoine': 'Avoine', 'ing.soupe': 'Soupe', 'ing.pates': 'Pâtes', 'ing.tomate': 'Tomate',
    'ing.saumon': 'Saumon', 'ing.riz_complet': 'Riz Complet', 'ing.asperges': 'Aspargos',
    'ing.poulet_roti': 'Poulet Rôti', 'ing.pomme_de_terre': 'Pomme de Terre', 'ing.legumes_vapeur': 'Légumes Vapeur',
    'ing.pain_perdu': 'Pain Perdu', 'ing.gateau_banane': 'Gâteau Banane', 'ing.risotto': 'Risotto',
    'ing.champignons': 'Champignons', 'ing.quiche': 'Quiche', 'ing.poireaux': 'Poireaux', 'ing.fromage': 'Fromage',
    'module.1.title': 'Le Bon Départ', 'module.2.title': 'Bébé Prêt à Manger ?', 'module.3.title': 'Les Aliments par Étape',
    'module.4.title': 'Textures en Confiance', 'module.5.title': 'Juste Quantité', 'module.6.title': 'Routine à la Française',
    'module.7.title': 'Les Erreurs à Éviter', 'module.8.title': 'L’Assiette Équilibrée',
    'module.1.desc': 'Comprendre les bases et le moment idéal pour commencer.',
    'module.2.desc': 'Identifier les signes de préparation de votre enfant.',
    'module.3.desc': 'La chronologie idéale pour introduire les nouveaux goûts.',
    'module.4.desc': 'Comment évoluer des purées aux morceaux en toute sécurité.',
    'module.5.desc': 'Écouter la satiété de votre bébé et éviter les pressions.',
    'module.6.desc': 'Organiser les repas autour de la vie de famille.',
    'module.7.desc': 'Ce qu\'il faut absolument éviter la première année.',
    'module.8.desc': 'Composer un repas complet, sain et nutritif.',
    'module.download': 'Télécharger', 'module.discover': 'Découvrir', 'module.exclusive': 'Exclusif pour les membres',
    'module.back': 'Retour', 'module.buy': 'Acheter',
    'bonus.1.title': 'Planner de menus pratiques pour bébé', 'bonus.2.title': 'Guide visuels introduction alimentaire', 'bonus.3.title': 'Recettes: Introduction alimentaire du bebe',
    'prod.1.title': 'Check list Hebdomadaire d’Alimentation du Bébé', 'prod.2.title': 'Le Guide Essentiel du BLW', 'prod.3.title': 'De 4 À 24 Mois L’Alimentation Complète De Bébé',
    'prod.4.title': 'Diversification Alimentaire Spéciale Intolérances + 20 Recettes Bébé Sans Allergènes', 'prod.5.title': '20 Recettes Bébé Sans Allergènes'
  },
  pt: {
    'nav.home': 'Início', 'nav.settings': 'Configurações', 'nav.planner': 'Meu Plano', 'nav.logout': 'Sair', 'nav.menu': 'Menu Principal',
    'dash.welcome': 'Olá, Mamãe', 'dash.welcome_badge': 'Bem-vinda à sua jornada', 'dash.subtitle': 'Tudo o que você precisa para uma introdução alimentar calma, nutritiva e cheia de descobertas.',
    'dash.modules': 'Módulos', 'dash.bonus': 'Bônus Exclusivos', 'dash.recommended': 'Sugestões para você',
    'dash.feedback.title': 'Gostou do NutriBebe?', 'dash.feedback.text': 'Sua opinião é fundamental para nós! Nossa equipe está pronta para te ouvir.',
    'dash.feedback.button': 'Enviar Feedback / Suporte', 'dash.app_mobile': 'App NutriBebe',
    'planner.title': 'Planejador Nutri', 'planner.subtitle': 'Um cardápio semanal de 7 dias pensado para a fase atual do seu bebê.',
    'planner.setup': 'Perfil do Bebê', 'planner.edit': 'Editar Perfil', 'planner.cancel': 'Cancelar',
    'planner.babyName': 'Como se chama o seu bebê?', 'planner.name_placeholder': 'Nome do bebê', 'planner.birthDate': 'Data de nascimento',
    'planner.method': 'Método de Introdução', 'planner.method.blw': 'BLW (Pedaços)', 'planner.method.traditional': 'Tradicional (Papinhas)', 'planner.method.mixed': 'Misto',
    'planner.restrictions': 'Restrições ou Alergias', 'planner.save': 'Salvar Perfil', 'planner.generate': 'Gerar Nova Semana',
    'planner.generate.desc': 'Quer variar os alimentos desta semana? Vamos criar um novo cardápio de 7 dias 💛',
    'planner.menu.week': 'Cardápio de 7 Dias', 'planner.shopping': 'Lista de Compras', 'planner.day': 'Dia',
    'planner.motivation': 'Cada nova cor no pratinho é um passo para uma vida saudável. Você está indo muito bem! 💛',
    'planner.disclaimer': 'Atenção: Este planejador é uma sugestão e não substitui o acompanhamento do seu pediatra.',
    'planner.empty': 'Configure o perfil para visualizar o cardápio.', 'planner.age.month': 'mês', 'planner.age.months': 'meses',
    'planner.milk.title': 'Ainda no leitinho!', 'planner.milk.desc': 'Seu bebê tem {age} meses. A OMS recomenda aleitamento exclusivo até os 6 meses. Volte aqui aos 6 meses! 💛',
    'settings.title': 'Sua Conta', 'settings.subtitle': 'Gerencie suas preferências.', 'settings.lang': 'Idioma do App', 'settings.save': 'Salvar Alterações', 'settings.saved': 'Alterações salvas!',
    'footer.curation': 'Curadoria em Introdução Alimentar',
    
    'auth.login.title': 'Bem-vinda de volta', 'auth.login.subtitle': 'Entre para continuar sua jornada.',
    'auth.register.title': 'Criar Conta', 'auth.register.subtitle': 'Junte-se à nossa comunidade de mamães.',
    'auth.email': 'Endereço de E-mail', 'auth.pass': 'Senha', 'auth.confirmPass': 'Confirmar Senha',
    'auth.placeholder.email': 'exemplo@email.com', 'auth.enter': 'Entrar', 'auth.createAccount': 'Cadastrar',
    'auth.forgotLink': 'Esqueceu a senha?', 'auth.noAccount': 'Não tem conta?', 'auth.registerHere': 'Cadastre-se aqui',
    'auth.hasAccount': 'Já tem conta?', 'auth.loginHere': 'Faça login',
    'auth.loading.enter': 'Entrando...', 'auth.loading.create': 'Criando...',
    'auth.error.invalid': 'E-mail ou senha inválidos.', 'auth.error.locked': 'Conta bloqueada temporariamente. Tente mais tarde.',
    'auth.error.exists': 'Este e-mail já está em uso.', 'auth.error.ip_limit': 'Apenas um cadastro é permitido por endereço IP.',
    'auth.error.match': 'As senhas não coincidem.',
    'auth.forgot.title': 'Recuperação', 'auth.forgot.subtitle': 'Digite seu e-mail para receber o link.',
    'auth.sendLink': 'Enviar Link', 'auth.backLogin': 'Voltar para Login',
    'auth.successReset': 'Link enviado com sucesso!', 'auth.checkInbox': 'Verifique sua caixa de entrada.',

    'meal.lunch': 'Almoço', 'meal.snack': 'Lanche', 'meal.dinner': 'Jantar', 'meal.ingredients_label': 'Alimentos usados:',
    'meal.l1': 'Delícia de Abóbora com Frango', 'meal.l2': 'Papinha de Carne e Cenoura', 'meal.l3': 'Mix de Chuchu e Feijão',
    'meal.l4': 'Creme de Ervilha com Ovo', 'meal.l5': 'Peixe Branco com Abobrinha', 'meal.l6': 'Couve-flor e Lentilha Rosa',
    'meal.l7': 'Espinafre com Carne Moída', 'meal.l8': 'Quinoa com Legumes e Carne', 'meal.l9': 'Arroz com Frango e Espinafre',
    'meal.l10': 'Peixe com Batatas', 'meal.l11': 'Omelete de Milho', 'meal.l12': 'Salmão e Arroz Integral', 'meal.l13': 'Frango Assado e Legumes',
    'meal.s1': 'Mamão em Cubos', 'meal.s2': 'Banana Amassadinha', 'meal.s3': 'Abacate Cremoso', 'meal.s4': 'Pera Macia',
    'meal.s5': 'Manga Fresca', 'meal.s6': 'Maçã Assada', 'meal.s7': 'Melão Refrescante', 'meal.s8': 'Iogurte com Banana',
    'meal.s9': 'Morango com Aveia', 'meal.s10': 'Maçã e Torradinha', 'meal.s11': 'Bolo de Banana e Aveia',
    'meal.d1': 'Jantar Leve de Abóbora', 'meal.d2': 'Mix de Frutas', 'meal.d3': 'Batata e Couve-flor', 'meal.d4': 'Arroz com Ervilhas',
    'meal.d5': 'Sopa de Abobrinha e Chuchu', 'meal.d6': 'Lentilha com Cenoura', 'meal.d7': 'Arroz com Brócolis', 'meal.d8': 'Sopa de Lentilha',
    'meal.d9': 'Macarrão com Tomate e Frango', 'meal.d10': 'Risoto de Espinafre', 'meal.d11': 'Quiche de Alho-poró',
    'ing.potiron': 'Abóbora', 'ing.poulet': 'Frango', 'ing.patateDouce': 'Batata Doce', 'ing.carotte': 'Cenoura',
    'ing.riz': 'Arroz', 'ing.viandeHachee': 'Carne Moída', 'ing.chayote': 'Chuchu', 'ing.haricots': 'Feijão',
    'ing.pommeDeTerre': 'Batata', 'ing.petitsPois': 'Ervilha', 'ing.oeuf': 'Ovo', 'ing.brocoli': 'Brócolis',
    'ing.abobrinha': 'Abobrinha', 'ing.poissonBlanc': 'Peixe Branco', 'ing.mais': 'Milho', 'ing.choufleur': 'Couve-flor',
    'ing.lentilles': 'Lentilha', 'ing.epinards': 'Espinafre', 'ing.papaye': 'Mamão', 'ing.banane': 'Banana',
    'ing.avocat': 'Abacate', 'ing.pear': 'Pera', 'ing.mango': 'Manga', 'ing.pomme': 'Maçã', 'ing.melon': 'Melão',
    'ing.boeuf': 'Carne Bovina', 'ing.quinoa': 'Quinoa', 'ing.yaourt': 'Iogurte', 'ing.fraise': 'Morango',
    'ing.avoine': 'Aveia', 'ing.soupe': 'Sopa', 'ing.pates': 'Macarrão', 'ing.tomate': 'Tomate', 'ing.saumon': 'Salmão',
    'ing.riz_complet': 'Arroz Integral', 'ing.asperges': 'Aspargos', 'ing.poulet_roti': 'Frango Assado',
    'ing.pomme_de_terre': 'Batata', 'ing.legumes_vapeur': 'Legumes no Vapor', 'ing.pain_perdu': 'Pãozinho',
    'ing.gateau_banane': 'Bolo de Banana', 'ing.risotto': 'Risoto', 'ing.champignons': 'Cogumelos',
    'ing.quiche': 'Quiche', 'ing.poireaux': 'Alho-poró', 'ing.fromage': 'Queijo',
    'module.1.title': 'O Bom Começo', 'module.2.title': 'Bebê Pronto para Comer?', 'module.3.title': 'Alimentos por Etapa',
    'module.4.title': 'Texturas com Confiança', 'module.5.title': 'Quantidade Certa', 'module.6.title': 'Rotina Leve',
    'module.7.title': 'Erros a Evitar', 'module.8.title': 'Pratinho Equilibrado',
    'module.1.desc': 'O início ideal para uma jornada alimentar de sucesso.',
    'module.2.desc': 'Saiba identificar se o seu bebê já está pronto para comer.',
    'module.3.desc': 'O passo a passo da introdução de cada grupo alimentar.',
    'module.4.desc': 'Como evoluir as texturas com segurança e confiança.',
    'module.5.desc': 'Entenda as quantidades ideais e o respeito à saciedade.',
    'module.6.desc': 'Como criar uma rotina leve e prazerosa à mesa.',
    'module.7.desc': 'O que evitar para garantir a saúde do seu pequeno.',
    'module.8.desc': 'Como montar o pratinho perfeito e nutritivo.',
    'module.download': 'Baixar Guia', 'module.discover': 'Descobrir', 'module.exclusive': 'Conteúdo exclusivo',
    'module.back': 'Voltar', 'module.buy': 'Acessar Agora',
    'bonus.1.title': 'Planner de menus práticos para o bebê', 'bonus.2.title': 'Guia visual de introdução alimentar', 'bonus.3.title': 'Receitas: Introdução alimentar do bebê',
    'prod.1.title': 'Check list Hebdomadaire d’Alimentation du Bébé', 'prod.2.title': 'Le Guide Essentiel du BLW', 'prod.3.title': 'De 4 À 24 Mois L’Alimentation Complète De Bébé',
    'prod.4.title': 'Diversification Alimentaire Spéciale Intolérances + 20 Recettes Bébé Sans Allergênes', 'prod.5.title': '20 Recettes Bébé Sans Allergênes'
  },
  en: {
    'nav.home': 'Home', 'nav.settings': 'Settings', 'nav.planner': 'My Plan', 'nav.logout': 'Logout', 'nav.menu': 'Main Menu',
    'dash.welcome': 'Welcome, Mom', 'dash.welcome_badge': 'Welcome to your journey', 'dash.subtitle': 'Everything you need for a calm, nutritious, and joyful food introduction journey.',
    'dash.modules': 'Modules', 'dash.bonus': 'Exclusive Bonuses', 'dash.recommended': 'Handpicked for you',
    'dash.feedback.title': 'Loving NutriBebe?', 'dash.feedback.text': 'Your feedback means the world to us!',
    'dash.feedback.button': 'Contact Support', 'dash.app_mobile': 'NutriBebe App',
    'planner.title': 'Weekly Planner', 'planner.subtitle': 'A 7-day personalized menu based on your baby\'s age and needs.',
    'planner.setup': 'Baby Profile', 'planner.edit': 'Edit Profile', 'planner.cancel': 'Cancel',
    'planner.babyName': 'What\'s your baby\'s name?', 'planner.name_placeholder': 'Baby\'s name', 'planner.birthDate': 'Birth Date',
    'planner.method': 'Feeding Method', 'planner.method.blw': 'BLW (Finger Foods)', 'planner.method.traditional': 'Traditional (Purees)', 'planner.method.mixed': 'Mixed',
    'planner.restrictions': 'Allergies', 'planner.save': 'Save Profile', 'planner.generate': 'Generate New Week',
    'planner.generate.desc': 'Want to vary the foods? Create a new 7-day menu 💛',
    'planner.menu.week': '7-Day Menu', 'planner.shopping': 'Shopping List', 'planner.day': 'Day',
    'planner.motivation': 'Every new flavor is a discovery! 💛',
    'planner.disclaimer': 'Important: This is a guide and does not replace your pediatrician\'s advice.',
    'planner.empty': 'Setup profile to see your menu.', 'planner.age.month': 'month', 'planner.age.months': 'months',
    'planner.milk.title': 'Still on milk!', 'planner.milk.desc': 'Your baby is {age} months old. WHO recommends exclusive breastfeeding until 6 months. 💛',
    'settings.title': 'Account', 'settings.subtitle': 'Manage your preferences.', 'settings.lang': 'Language', 'settings.save': 'Save', 'settings.saved': 'Saved!',
    'footer.curation': 'Curation in Food Introduction',
    
    'auth.login.title': 'Welcome back', 'auth.login.subtitle': 'Log in to continue your adventure.',
    'auth.register.title': 'Create Account', 'auth.register.subtitle': 'Join our community of moms.',
    'auth.email': 'Email Address', 'auth.pass': 'Password', 'auth.confirmPass': 'Confirm Password',
    'auth.placeholder.email': 'example@email.com', 'auth.enter': 'Log In', 'auth.createAccount': 'Sign Up',
    'auth.forgotLink': 'Forgot password?', 'auth.noAccount': 'No account?', 'auth.registerHere': 'Register here',
    'auth.hasAccount': 'Already have an account?', 'auth.loginHere': 'Log in here',
    'auth.loading.enter': 'Logging in...', 'auth.loading.create': 'Creating...',
    'auth.error.invalid': 'Invalid email or password.', 'auth.error.locked': 'Account locked temporarily. Try later.',
    'auth.error.exists': 'This email is already in use.', 'auth.error.ip_limit': 'Only one registration is allowed per IP address.',
    'auth.error.match': 'Passwords do not match.',
    'auth.forgot.title': 'Recovery', 'auth.forgot.subtitle': 'Enter your email to receive a link.',
    'auth.sendLink': 'Send Link', 'auth.backLogin': 'Back to Login',
    'auth.successReset': 'Link sent successfully!', 'auth.checkInbox': 'Check your inbox.',

    'meal.lunch': 'Lunch', 'meal.snack': 'Snack', 'meal.dinner': 'Dinner', 'meal.ingredients_label': 'Ingredients:',
    'meal.l1': 'Pumpkin Chicken Delight', 'meal.l2': 'Sweet Beef and Carrot Puree', 'meal.l3': 'Chayote and Bean Mix',
    'meal.l4': 'Pea and Egg Cream', 'meal.l5': 'White Fish and Zucchini', 'meal.l6': 'Cauliflower and Pink Lentils',
    'meal.l7': 'Spinach and Ground Beef', 'meal.l8': 'Veggie Quinoa and Beef', 'meal.l9': 'Chicken Rice and Spinach',
    'meal.l10': 'Fish and Potatoes', 'meal.l11': 'Sweet Corn Omelet', 'meal.l12': 'Salmon and Brown Rice', 'meal.l13': 'Roasted Chicken and Veggies',
    'meal.s1': 'Papaya Cubes', 'meal.s2': 'Mashed Banana', 'meal.s3': 'Creamy Avocado', 'meal.s4': 'Soft Pear',
    'meal.s5': 'Fresh Mango', 'meal.s6': 'Baked Apple', 'meal.s7': 'Refreshing Melon', 'meal.s8': 'Yogurt and Banana',
    'meal.s9': 'Strawberry and Oats', 'meal.s10': 'Apple and Toast', 'meal.s11': 'Banana Oat Cake',
    'meal.d1': 'Light Pumpkin Dinner', 'meal.d2': 'Fruity Banana Mango Mix', 'meal.d3': 'Potato and Cauliflower', 'meal.d4': 'Pea Rice',
    'meal.d5': 'Zucchini and Chayote Soup', 'meal.d6': 'Lentils with Carrots', 'meal.d7': 'Broccoli Rice', 'meal.d8': 'Lentil Soup',
    'meal.d9': 'Tomato Chicken Pasta', 'meal.d10': 'Spinach Risotto', 'meal.d11': 'Leek Quiche',
    'ing.potiron': 'Pumpkin', 'ing.poulet': 'Chicken', 'ing.patateDouce': 'Sweet Potato', 'ing.carotte': 'Carrot',
    'ing.riz': 'Rice', 'ing.viandeHachee': 'Ground Beef', 'ing.chayote': 'Chayote', 'ing.haricots': 'Beans',
    'ing.pommeDeTerre': 'Potato', 'ing.petitsPois': 'Peas', 'ing.oeuf': 'Egg', 'ing.brocoli': 'Broccoli',
    'ing.abobrinha': 'Zucchini', 'ing.poissonBlanc': 'White Fish', 'ing.mais': 'Corn', 'ing.choufleur': 'Cauliflower',
    'ing.lentilles': 'Lentils', 'ing.epinards': 'Spinach', 'ing.papaye': 'Papaya', 'ing.banane': 'Banana',
    'ing.avocat': 'Avocado', 'ing.pear': 'Pear', 'ing.mango': 'Mango', 'ing.pomme': 'Apple', 'ing.melon': 'Melon',
    'ing.boeuf': 'Beef', 'ing.quinoa': 'Quinoa', 'ing.yaourt': 'Yogurt', 'ing.fraise': 'Strawberry',
    'ing.avoine': 'Oats', 'ing.soupe': 'Soup', 'ing.pates': 'Pasta', 'ing.tomate': 'Tomato', 'ing.saumon': 'Salmon',
    'ing.riz_complet': 'Brown Rice', 'ing.asperges': 'Asparagus', 'ing.poulet_roti': 'Roasted Chicken',
    'ing.pomme_de_terre': 'Potato', 'ing.legumes_vapeur': 'Steamed Veggies', 'ing.pain_perdu': 'Toast',
    'ing.gateau_banane': 'Banana Cake', 'ing.risotto': 'Risotto', 'ing.champignons': 'Mushrooms',
    'ing.quiche': 'Quiche', 'ing.poireaux': 'Leeks', 'ing.fromage': 'Cheese',
    'module.1.title': 'The Good Start', 'module.2.title': 'Is Baby Ready?', 'module.3.title': 'Step-by-Step Food',
    'module.4.title': 'Confidence Textures', 'module.5.title': 'Right Amount', 'module.6.title': 'Light Routine',
    'module.7.title': 'Errors to Avoid', 'module.8.title': 'Balanced Plate',
    'module.1.desc': 'The perfect start for a successful food journey.',
    'module.2.desc': 'Learn how to identify if your baby is ready to eat.',
    'module.3.desc': 'Step-by-step guide to introducing each food group.',
    'module.4.desc': 'How to evolve textures with safety and confidence.',
    'module.5.desc': 'Understand ideal portions and respect satiety.',
    'module.6.desc': 'How to create a light and enjoyable table routine.',
    'module.7.desc': 'What to avoid to ensure your little one\'s health.',
    'module.8.desc': 'How to build the perfect and nutritious plate.',
    'module.download': 'Download', 'module.discover': 'Discover', 'module.exclusive': 'Exclusive content',
    'module.back': 'Back', 'module.buy': 'Buy Now',
    'bonus.1.title': 'Practical baby menu planner', 'bonus.2.title': 'Visual food introduction guide', 'bonus.3.title': 'Recipes: Baby food introduction',
    'prod.1.title': 'Check list Weekly Baby Feeding', 'prod.2.title': 'The Essential BLW Guide', 'prod.3.title': 'From 4 To 24 Months Complete Baby Nutrition',
    'prod.4.title': 'Special Dietary Diversification for Intolerances + 20 Allergen Free Baby Recipes', 'prod.5.title': '20 Allergen Free Baby Recipes'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('nutribebe-lang') as Language) || 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('nutribebe-lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
