
import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'fr' | 'pt' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    'nav.home': 'Accueil',
    'nav.settings': 'Paramètres',
    'nav.planner': 'Mon Plan',
    'nav.logout': 'Déconnexion',
    'nav.menu': 'Menu Principal',
    'dash.welcome': 'Bienvenue, Maman',
    'dash.subtitle': 'Tout ce dont vous avez besoin pour une diversification alimentaire sereine, nutritive et pleine d\'amour.',
    'dash.bonus': 'Bonus Exclusifs',
    'dash.recommended': 'Sélectionnés pour vous',
    'dash.feedback.title': 'Vous aimez NutriBebe ?',
    'dash.feedback.text': 'Votre avis est précieux ! Si vous avez des suggestions, des questions ou si vous souhaitez simplement nous dire à quel point vous appréciez l\'appli, nous sommes à votre écoute.',
    'dash.feedback.button': 'Contacter le Support',
    'planner.title': 'Menu de la Semaine',
    'planner.subtitle': 'Un guide personnalisé selon l\'âge et les besoins de votre bébé.',
    'planner.setup': 'Profil du Bébé',
    'planner.edit': 'Modifier le profil',
    'planner.cancel': 'Annuler',
    'planner.babyName': 'Comment s\'appelle votre petit trésor ?',
    'planner.birthDate': 'Sa date de naissance',
    'planner.method': 'Méthode choisie',
    'planner.method.blw': 'DME (Morceaux)',
    'planner.method.traditional': 'Classique (Purées)',
    'planner.method.mixed': 'Mixte',
    'planner.restrictions': 'Allergies ou aversions',
    'planner.save': 'Enregistrer le profil',
    'planner.generate': 'Générer une nouvelle semaine',
    'planner.generate.desc': 'Voulez-vous changer les repas de cette semaine ? Créons un nouveau menu de 7 jours 💛',
    'planner.menu.week': 'Menu de 7 Jours',
    'planner.shopping': 'Liste de Courses',
    'planner.day': 'Jour',
    'planner.motivation': 'Chaque bouchée est une nouvelle découverte. Vous faites un travail merveilleux ! 💛',
    'planner.disclaimer': 'Important : Ce plan est un guide nutritionnel et ne remplace pas les conseils personnalisés de votre pédiatre.',
    'planner.empty': 'Veuillez configurer le profil pour voir le menu.',
    'planner.age.month': 'mois',
    'planner.age.months': 'mois',
    'planner.milk.title': 'Toujours au lait !',
    'planner.milk.desc': 'Votre bébé a {age} mois. L\'OMS recommande l\'allaitement exclusif jusqu\'à 6 mois. Continuez l\'allaitement ou le biberon et revenez ici à ses 6 mois ! 💛',
    'module.back': 'Retour',
    'module.download': 'Télécharger le Guide PDF',
    'module.exclusive': 'Contenu numérique de haute qualité',
    'settings.title': 'Préférences',
    'settings.subtitle': 'Personnalisez votre expérience dans l\'application.',
    'settings.lang': 'Langue d\'affichage',
    'settings.save': 'Enregistrer les modifications',
    'settings.saved': 'Modifications enregistrées !',
    'auth.login.title': 'NutriBebe',
    'auth.login.subtitle': 'L\'espace maman pour une alimentation saine.',
    'auth.enter': 'Se connecter',

    // Labels de repas
    'meal.lunch': 'Déjeuner',
    'meal.snack': 'Goûter',
    'meal.dinner': 'Dîner',
    'meal.ingredients_label': 'Aliments utilisés :',

    // --- MEALS INTRO (6-8m) ---
    'meal.intro.l1.traditional': 'Purée lisse de Potiron et Poulet',
    'meal.intro.l1.blw': 'Bâtonnets de Potiron fondants et effiloché de Poulet',
    'meal.intro.l1.mixed': 'Purée de Potiron et petits grains de Poulet',
    'meal.intro.l2.traditional': 'Purée lisse de Patate Douce et Carotte',
    'meal.intro.l2.blw': 'Bâtonnets de Patate Douce et Carotte à la vapeur',
    'meal.intro.l2.mixed': 'Écrasé de Patate Douce avec dés de Carotte',
    'meal.intro.l3.traditional': 'Purée lisse de Chayote et Panais',
    'meal.intro.l3.blw': 'Quartiers de Chayote et Panais fondants',
    'meal.intro.l3.mixed': 'Purée de Chayote avec morceaux de Panais',
    'meal.intro.l4.traditional': 'Soupe lisse de Petits Pois et Pommes de Terre',
    'meal.intro.l4.blw': 'Petits Pois entiers écrasés et bâtonnets de Pommes de Terre',
    'meal.intro.l4.mixed': 'Soupe de Petits Pois avec dés de Pommes de Terre',
    'meal.intro.l5.traditional': 'Purée lisse de Courgettes et Bœuf haché',
    'meal.intro.l5.blw': 'Rondelles de Courgettes et Bœuf en lanières tendres',
    'meal.intro.l5.mixed': 'Purée de Courgettes avec Bœuf effiloché',
    'meal.intro.l6.traditional': 'Purée lisse de Chou-fleur et Poisson blanc',
    'meal.intro.l6.blw': 'Bouquets de Chou-fleur et filet de Poisson',
    'meal.intro.l6.mixed': 'Écrasé de Chou-fleur avec miettes de Poisson',
    'meal.intro.l7.traditional': 'Purée lisse de Brocoli et Jaune d\'œuf',
    'meal.intro.l7.blw': 'Gros bouquets de Brocoli et quartier d\'œuf dur',
    'meal.intro.l7.mixed': 'Purée de Brocoli avec Jaune d\'œuf émietté',

    'meal.intro.s1.traditional': 'Purée de Papaye mixée',
    'meal.intro.s1.blw': 'Tranche de Papaye fondante (sans pépins)',
    'meal.intro.s1.mixed': 'Papaye grossièrement écrasée',
    'meal.intro.s2.traditional': 'Purée de Banane mixée',
    'meal.intro.s2.blw': 'Banane entière épluchée (très mûre)',
    'meal.intro.s2.mixed': 'Banane écrasée à la fourchette',
    'meal.intro.s3.traditional': 'Purée d\'Avocat mixé',
    'meal.intro.s3.blw': 'Quartiers d\'Avocat fondant',
    'meal.intro.s3.mixed': 'Écrasé d\'Avocat',

    'ing.potiron': 'Potiron',
    'ing.poulet': 'Blanc de Poulet',
    'ing.patateDouce': 'Patate Douce',
    'ing.carotte': 'Carotte',
    'ing.chayote': 'Chayote',
    'ing.panais': 'Panais',
    'ing.petitsPois': 'Petits Pois',
    'ing.pommeDeTerre': 'Pomme de Terre',
    'ing.papaye': 'Papaye',
    'ing.banane': 'Banane',
    'ing.pomme': 'Pomme',
    'ing.avocat': 'Avocat',
    'ing.lentillesCorail': 'Lentilles Corail',
    'ing.epinards': 'Épinards',
    'ing.igname': 'Igname',
    'ing.brocoli': 'Brocoli',
    'ing.manioc': 'Manioc',
    'ing.viandeHachee': 'Viande Hachée',
    'ing.choufleur': 'Chou-fleur',
    'ing.jauneOeuf': 'Jaune d\'Œuf',
    'ing.rizComplet': 'Riz Complet',
    'ing.haricots': 'Haricots Noirs',
    'ing.patesMais': 'Pâtes de Maïs',
    'ing.pouletEffiloche': 'Poulet Effiloché',
    'ing.tomate': 'Tomate',
    'ing.poisChiches': 'Pois Chiches',
    'ing.poissonBlanc': 'Poisson Blanc',
    'ing.azeite': 'Huile d\'Olive',
    'ing.rizArboreo': 'Riz à Risotto',
    'ing.viandeIscas': 'Iscas de Bœuf',
    'ing.yaourtNature': 'Yaourt Nature',
    'ing.avoine': 'Avoine',
    'ing.mangue': 'Mangue',
    'ing.oeuf': 'Œuf',
    'ing.farineAvoine': 'Farine d\'Avoine',
    'ing.poire': 'Poire',
    'ing.cannelle': 'Cannelle',
    'ing.fromageFrais': 'Fromage Frais',
    'ing.couscous': 'Couscous',
    'ing.abobrinha': 'Courgette',
    'ing.salsa': 'Persil',
    'ing.betterave': 'Betterave',
    'ing.patesIntegral': 'Pâtes Complètes',
    'ing.sauceTomate': 'Sauce Tomate Maison',
    'ing.tilapia': 'Tilapia',
    'ing.lentille': 'Lentille',
    'ing.boeuf': 'Bœuf',
    'ing.cremeLeite': 'Crème Fraîche',
    'ing.painIntegral': 'Pain Complet',
    'ing.raisin': 'Raisin',
    'ing.fraise': 'Fraise',
    'ing.pasteque': 'Pastèque',
    'ing.trigoIntegral': 'Blé Complet',
    'ing.lait': 'Lait',
    'ing.patesAlpha': 'Pâtes Alphabet',
    'ing.vagem': 'Haricots Verts',
    'ing.alhoPoro': 'Poireau',
    'ing.tomateCerise': 'Tomate Cerise',
    'ing.salmo': 'Saumon',
    'ing.limon': 'Citron Sicilien',
    'ing.couve': 'Chou Vert',
    'ing.oignon': 'Oignon',

    'module.1.title': 'Le grand départ : Quand commencer ?',
    'module.1.desc': 'Comprenez pourquoi attendre 6 mois et comment préparer les premiers repas en toute sécurité.',
    'module.2.title': 'Les 5 signes de préparation',
    'module.2.desc': 'Tient-il assis ? S\'intéresse-t-il à votre assiette ? Apprenez à observer votre bébé.',
    'module.3.title': 'Le Guide des Aliments par Étape',
    'module.3.desc': 'Fruits, légumes, protéines et céréales : le bon ordre pour introduire chaque saveur.',
    'module.4.title': 'L\'évolution des textures',
    'module.4.desc': 'Du lisse au mouliné, puis aux morceaux fondants. Évitez les réflexes nauséeux.',
    'module.5.title': 'L\'appétit de bébé : Les quantités',
    'module.5.desc': 'Ne forcez jamais. Apprenez à reconnaître les signes de satiété pour un rapport sain à la nourriture.',
    'module.6.title': 'La routine des 4 repas',
    'module.6.desc': 'Petit-déjeuner, déjeuner, goûter et dîner : organiser la journée autour du lait et des solides.',
    'module.7.title': 'Les interdits avant 12 mois',
    'module.7.desc': 'Sel, sucre, miel et aliments étouffants : tout ce qu\'il faut garder hors de portée.',
    'module.8.title': 'Composer une assiette équilibrée',
    'module.8.desc': 'La règle du tiers : vitamines, fer et énergie dans chaque repas.',
    
    'bonus.1.title': 'Guide visuels introduction alimentaire',
    'bonus.2.title': 'Introduction alimentaire du bebe + Recettes',
    'bonus.3.title': 'Planner de menus pratiques pour bébé – Introduction alimentaire',
  },
  pt: {
    'nav.home': 'Início',
    'nav.settings': 'Configurações',
    'nav.planner': 'Meu Plano',
    'nav.logout': 'Sair',
    'nav.menu': 'Menu Principal',
    'dash.welcome': 'Olá, Mamãe',
    'dash.subtitle': 'Tudo o que você precisa para uma introdução alimentar calma, nutritiva e cheia de descobertas.',
    'dash.bonus': 'Bônus Exclusivos',
    'dash.recommended': 'Sugestões para você',
    'dash.feedback.title': 'Gostou do NutriBebe?',
    'dash.feedback.text': 'Sua opinião é fundamental para nós! Se tiver sugestões, dúvidas ou quiser apenas compartilhar sua experiência positiva, nossa equipe de suporte está pronta para te ouvir.',
    'dash.feedback.button': 'Enviar Feedback / Suporte',
    'planner.title': 'Planejador Nutri',
    'planner.subtitle': 'Um cardápio semanal de 7 dias pensado para a fase atual do seu bebê.',
    'planner.setup': 'Perfil do Bebê',
    'planner.edit': 'Editar Perfil',
    'planner.cancel': 'Cancelar',
    'planner.babyName': 'Como se chama o seu bebê?',
    'planner.birthDate': 'Data de nascimento',
    'planner.method': 'Método de Introdução',
    'planner.method.blw': 'BLW (Pedaços)',
    'planner.method.traditional': 'Tradicional (Papinhas)',
    'planner.method.mixed': 'Misto',
    'planner.restrictions': 'Restrições ou Alergias',
    'planner.save': 'Salvar Perfil',
    'planner.generate': 'Gerar Nova Semana',
    'planner.generate.desc': 'Quer variar os alimentos desta semana? Vamos criar um novo cardápio de 7 dias 💛',
    'planner.menu.week': 'Cardápio de 7 Dias',
    'planner.shopping': 'Lista de Compras',
    'planner.day': 'Dia',
    'planner.motivation': 'Cada nova cor no pratinho é um passo para uma vida saudável. Você está indo muito bem! 💛',
    'planner.disclaimer': 'Atenção: Este planejador é uma sugestão nutricional e não substitui o acompanhamento do seu pediatra ou nutricionista infantil.',
    'planner.empty': 'Configure o perfil do seu bebê para visualizar o cardápio personalizado.',
    'planner.age.month': 'mês',
    'planner.age.months': 'meses',
    'planner.milk.title': 'Ainda no leitinho!',
    'planner.milk.desc': 'Seu bebê tem {age} meses. A OMS recomenda aleitamento exclusivo até os 6 meses. Continue no peito ou fórmula e volte aqui aos 6 meses! 💛',
    'module.back': 'Voltar',
    'module.download': 'Baixar Guia Completo PDF',
    'module.exclusive': 'Conteúdo educativo exclusivo para assinantes',
    'settings.title': 'Sua Conta',
    'settings.subtitle': 'Ajuste o idioma e gerencie sua sessão.',
    'settings.lang': 'Idioma do Aplicativo',
    'settings.save': 'Salvar Alterações',
    'settings.saved': 'Alterações salvas com sucesso!',

    // Labels de refeição
    'meal.lunch': 'Almoço',
    'meal.snack': 'Lanche',
    'meal.dinner': 'Jantar',
    'meal.ingredients_label': 'Alimentos usados:',

    // --- REFEIÇÕES INTRO (6-8m) ---
    'meal.intro.l1.traditional': 'Papinha de Abóbora e Frango',
    'meal.intro.l1.blw': 'Bastões de Abóbora cozida e Frango desfiado',
    'meal.intro.l1.mixed': 'Papinha de Abóbora com fiapos de Frango',
    'meal.intro.l2.traditional': 'Papinha de Batata Doce com Cenoura',
    'meal.intro.l2.blw': 'Batata Doce e Cenoura em cortes seguros',
    'meal.intro.l2.mixed': 'Purê de Batata Doce com Cenoura em cubinhos',
    'meal.intro.l3.traditional': 'Papinha de Chuchu com Mandioquinha',
    'meal.intro.l3.blw': 'Chuchu e Mandioquinha em fatias macias',
    'meal.intro.l3.mixed': 'Purê de Chuchu com pedaços de Mandioquinha',
    'meal.intro.l4.traditional': 'Papinha de Ervilha com Batata',
    'meal.intro.l4.blw': 'Ervilha amassada e Batata em bastões',
    'meal.intro.l4.mixed': 'Sopa de Ervilha com cubinhos de Batata',
    'meal.intro.l5.traditional': 'Papinha de Abobrinha e Carne moída',
    'meal.intro.l5.blw': 'Rodelas de Abobrinha e Carne em tiras macias',
    'meal.intro.l5.mixed': 'Purê de Abobrinha com Carne desfiada',
    'meal.intro.l6.traditional': 'Papinha de Couve-Flor e Peixe',
    'meal.intro.l6.blw': 'Floretes de Couve-Flor e Iscas de Peixe',
    'meal.intro.l6.mixed': 'Couve-Flor amassada com lascas de Peixe',
    'meal.intro.l7.traditional': 'Papinha de Brócolis e Gema de Ovo',
    'meal.intro.l7.blw': 'Floretes de Brócolis e Gema de Ovo cozida',
    'meal.intro.l7.mixed': 'Purê de Brócolis com Gema de Ovo amassada',

    'meal.intro.s1.traditional': 'Papinha de Mamão Papaia',
    'meal.intro.s1.blw': 'Fatia de Mamão Papaia (Corte Seguro)',
    'meal.intro.s1.mixed': 'Mamão Papaia amassado com garfo',
    'meal.intro.s2.traditional': 'Papinha de Banana Prata',
    'meal.intro.s2.blw': 'Banana inteira descascada (bem madura)',
    'meal.intro.s2.mixed': 'Banana amassada com garfo',
    'meal.intro.s3.traditional': 'Purê de Abacate batido',
    'meal.intro.s3.blw': 'Fatia de Abacate maduro',
    'meal.intro.s3.mixed': 'Abacate amassado',

    'ing.potiron': 'Abóbora',
    'ing.poulet': 'Frango',
    'ing.patateDouce': 'Batata Doce',
    'ing.carotte': 'Cenoura',
    'ing.chayote': 'Chuchu',
    'ing.panais': 'Mandioquinha',
    'ing.petitsPois': 'Ervilha',
    'ing.pommeDeTerre': 'Batata',
    'ing.papaye': 'Mamão Papaia',
    'ing.banane': 'Banana',
    'ing.pomme': 'Maçã',
    'ing.avocat': 'Abacate',
    'ing.lentillesCorail': 'Lentilha',
    'ing.epinards': 'Espinafre',
    'ing.igname': 'Inhame',
    'ing.brocoli': 'Brócolis',
    'ing.manioc': 'Mandioca',
    'ing.viandeHachee': 'Carne moída',
    'ing.choufleur': 'Couve-flor',
    'ing.jauneOeuf': 'Gema de ovo',
    'ing.rizComplet': 'Arroz Integral',
    'ing.haricots': 'Feijão',
    'ing.patesMais': 'Macarrão de Milho',
    'ing.pouletEffiloche': 'Frango Desfiado',
    'ing.tomate': 'Tomate',
    'ing.poisChiches': 'Grão de Bico',
    'ing.poissonBlanc': 'Peixe Branco',
    'ing.azeite': 'Azeite de Oliva',
    'ing.rizArboreo': 'Arroz',
    'ing.viandeIscas': 'Carne em Iscas',
    'ing.yaourtNature': 'Iogurte Natural',
    'ing.avoine': 'Aveia',
    'ing.mangue': 'Manga',
    'ing.oeuf': 'Ovo',
    'ing.farineAvoine': 'Farinha de Aveia',
    'ing.poire': 'Pera',
    'ing.cannelle': 'Canela',
    'ing.fromageFrais': 'Queijo Branco',
    'ing.couscous': 'Cuscuz',
    'ing.abobrinha': 'Abobrinha',
    'ing.salsa': 'Salsa',
    'ing.betterave': 'Beterraba',
    'ing.patesIntegral': 'Macarrão Integral',
    'ing.sauceTomate': 'Molho de Tomate',
    'ing.tilapia': 'Tilápia',
    'ing.lentille': 'Lentilha',
    'ing.boeuf': 'Carne',
    'ing.cremeLeite': 'Creme de Leite',
    'ing.painIntegral': 'Pão Integral',
    'ing.raisin': 'Uva',
    'ing.fraise': 'Morango',
    'ing.pasteque': 'Melancia',
    'ing.trigoIntegral': 'Trigo Integral',
    'ing.lait': 'Leite',
    'ing.patesAlpha': 'Macarrão Letrinhas',
    'ing.vagem': 'Vagem',
    'ing.alhoPoro': 'Alho Poró',
    'ing.tomateCerise': 'Tomate Cereja',
    'ing.salmo': 'Salmão',
    'ing.limon': 'Limão',
    'ing.couve': 'Couve',
    'ing.oignon': 'Cebola',

    'module.1.title': 'O Início de Tudo: Quando Começar?',
    'module.1.desc': 'Entenda a importância dos 6 meses e como preparar o ambiente para as primeiras colheradas.',
    'module.2.title': 'Sinais de Prontidão: O Bebê está Pronto?',
    'module.2.desc': 'Sentar sem apoio, interesse pela comida e reflexo de protrusão. Saiba o que observar.',
    'module.3.title': 'O Guia de Alimentos por Fase',
    'module.3.desc': 'Frutas de introdução, legumes coloridos e as primeiras proteínas. O que oferecer primeiro.',
    'module.4.title': 'Evolução de Texturas: Sem Medo',
    'module.4.desc': 'Como evoluir da textura lisa para a amassada e chegar aos pedaços com segurança.',
    'module.5.title': 'Quanto o Bebê Deve Comer?',
    'module.5.desc': 'Respeitando a saciedade. Entenda que o estômago do bebê é pequeno e o leite ainda é importante.',
    'module.6.title': 'A Rotina Alimentar Ideal',
    'module.6.desc': 'Como encaixar as refeições no dia a dia sem estresse, mantendo as sonecas e o aleitamento.',
    'module.7.title': 'Alimentos Proibidos antes de 1 Ano',
    'module.7.desc': 'Sal, açúcar, mel, sucos e ultraprocessados. Saiba o porquê de evitá-los agora.',
    'module.8.title': 'Montando o Prato Perfeito',
    'module.8.desc': 'Equilíbrio entre grupos alimentares: cores, ferro e energia em cada refeição.',
    
    'bonus.1.title': 'Guia visual de introdução alimentar',
    'bonus.2.title': 'Introdução alimentar do bebê + Receitas',
    'bonus.3.title': 'Planner de menus práticos para o bebê – Introdução alimentar',
  },
  en: {
    'nav.home': 'Home',
    'nav.settings': 'Settings',
    'nav.planner': 'My Plan',
    'nav.logout': 'Logout',
    'nav.menu': 'Main Menu',
    'dash.welcome': 'Welcome, Mom',
    'dash.subtitle': 'Everything you need for a calm, nutritious, and joyful food introduction journey.',
    'dash.bonus': 'Exclusive Bonuses',
    'dash.recommended': 'Handpicked for you',
    'dash.feedback.title': 'Loving NutriBebe?',
    'dash.feedback.text': 'Your feedback means the world to us! If you have suggestions, questions, or just want to share how much you like the app, we are here for you.',
    'dash.feedback.button': 'Contact Support / Feedback',
    'planner.title': 'Weekly Planner',
    'planner.subtitle': 'A 7-day personalized menu based on your baby\'s age and needs.',
    'planner.setup': 'Baby Profile',
    'planner.edit': 'Edit Profile',
    'planner.cancel': 'Cancel',
    'planner.babyName': 'What\'s your baby\'s name?',
    'planner.birthDate': 'Birth Date',
    'planner.method': 'Feeding Method',
    'planner.method.blw': 'BLW (Finger Foods)',
    'planner.method.traditional': 'Traditional (Purees)',
    'planner.method.mixed': 'Mixed',
    'planner.restrictions': 'Allergies or Restrictions',
    'planner.save': 'Save Profile',
    'planner.generate': 'Generate New Week',
    'planner.generate.desc': 'Want to vary the foods this week? Let\'s create a new 7-day menu 💛',
    'planner.menu.week': '7-Day Menu',
    'planner.shopping': 'Shopping List',
    'planner.day': 'Day',
    'planner.motivation': 'Every new flavor is a discovery. You\'re doing an amazing job! 💛',
    'planner.disclaimer': 'Important: This planner is a nutritional guide and does not replace professional medical advice from your pediatrician.',
    'planner.empty': 'Please setup your baby\'s profile to see your personalized menu.',
    'planner.age.month': 'month',
    'planner.age.months': 'months',
    'planner.milk.title': 'Still on milk!',
    'planner.milk.desc': 'Your baby is {age} months old. WHO recommends exclusive breastfeeding until 6 months. Keep breastfeeding or bottle and come back at 6 months! 💛',
    'module.back': 'Back',
    'module.download': 'Download PDF Guide',
    'module.exclusive': 'Exclusive high-quality digital content',
    'settings.title': 'Your Account',
    'settings.subtitle': 'Manage your language and session preferences.',
    'settings.lang': 'App Language',
    'settings.save': 'Save Changes',
    'settings.saved': 'Changes saved successfully!',

    // Meal Labels
    'meal.lunch': 'Lunch',
    'meal.snack': 'Snack',
    'meal.dinner': 'Dinner',
    'meal.ingredients_label': 'Ingredients used:',

    // --- MEALS INTRO (6-8m) ---
    'meal.intro.l1.traditional': 'Smooth Pumpkin and Chicken Puree',
    'meal.intro.l1.blw': 'Steamed Pumpkin sticks and shredded Chicken',
    'meal.intro.l1.mixed': 'Pumpkin Puree with thin Chicken threads',

    // Ingredients
    'ing.potiron': 'Pumpkin',
    'ing.poulet': 'Chicken',
    'ing.patateDouce': 'Sweet Potato',
    'ing.carotte': 'Carrot',
    'ing.chayote': 'Chayote',
    'ing.panais': 'Parsnip',
    'ing.petitsPois': 'Peas',
    'ing.pommeDeTerre': 'Potato',
    'ing.papaye': 'Papaya',
    'ing.banane': 'Banana',
    'ing.pomme': 'Apple',
    'ing.avocat': 'Avocado',
    'ing.lentillesCorail': 'Lentils',
    'ing.epinards': 'Spinach',
    'ing.igname': 'Yam',
    'ing.brocoli': 'Broccoli',
    'ing.manioc': 'Cassava',
    'ing.viandeHachee': 'Ground beef',
    'ing.choufleur': 'Cauliflower',
    'ing.jauneOeuf': 'Egg yolk',
    'ing.rizComplet': 'Brown Rice',
    'ing.haricots': 'Beans',
    'ing.patesMais': 'Corn Pasta',
    'ing.pouletEffiloche': 'Shredded Chicken',
    'ing.tomate': 'Tomato',
    'ing.poisChiches': 'Chickpeas',
    'ing.poissonBlanc': 'White Fish',
    'ing.azeite': 'Olive Oil',
    'ing.rizArboreo': 'Rice',
    'ing.viandeIscas': 'Beef Strips',
    'ing.yaourtNature': 'Natural Yogurt',
    'ing.avoine': 'Oats',
    'ing.mangue': 'Mango',
    'ing.oeuf': 'Egg',
    'ing.farineAvoine': 'Oat Flour',
    'ing.poire': 'Pear',
    'ing.cannelle': 'Cinnamon',
    'ing.fromageFrais': 'Soft Cheese',
    'ing.couscous': 'Couscous',
    'ing.abobrinha': 'Zucchini',
    'ing.salsa': 'Parsley',
    'ing.betterave': 'Beetroot',
    'ing.patesIntegral': 'Whole Wheat Pasta',
    'ing.sauceTomate': 'Tomato Sauce',
    'ing.tilapia': 'Tilapia',
    'ing.lentille': 'Lentil',
    'ing.boeuf': 'Beef',
    'ing.cremeLeite': 'Heavy Cream',
    'ing.painIntegral': 'Whole Wheat Bread',
    'ing.raisin': 'Grapes',
    'ing.fraise': 'Strawberry',
    'ing.pasteque': 'Watermelon',
    'ing.trigoIntegral': 'Whole Wheat',
    'ing.lait': 'Milk',
    'ing.patesAlpha': 'Alphabet Pasta',
    'ing.vagem': 'Green Beans',
    'ing.alhoPoro': 'Leek',
    'ing.tomateCerise': 'Cherry Tomato',
    'ing.salmo': 'Salmon',
    'ing.limon': 'Lemon',
    'ing.couve': 'Cabbage',
    'ing.oignon': 'Onion',

    'module.1.title': 'The Great Start: When to Begin?',
    'module.1.desc': 'Understand why 6 months is the golden rule and how to prepare for the first bite.',
    'module.2.title': 'Readiness Signs: Is Baby Ready?',
    'module.2.desc': 'Sitting up, showing interest, and losing the tongue-thrust reflex. What to watch for.',
    'module.3.title': 'The Food Guide by Stage',
    'module.3.desc': 'First fruits, colorful veggies, and early proteins. The best sequence for flavors.',
    'module.4.title': 'Texture Evolution: Be Confident',
    'module.4.desc': 'How to move from smooth purees to mashed food and safe finger foods.',
    'module.5.title': 'How Much Should Baby Eat?',
    'module.5.desc': 'Respecting fullness. Understand your baby\'s small stomach and the role of milk.',
    'module.6.title': 'The Ideal Feeding Routine',
    'module.6.desc': 'How to fit meals into your daily life without stress, balancing naps and milk.',
    'module.7.title': 'Forbidden Foods Before 12 Months',
    'module.7.desc': 'Salt, sugar, honey, juice, and choking hazards. Know why to avoid them now.',
    'module.8.title': 'Building the Perfect Plate',
    'module.8.desc': 'The rule of thirds: vitamins, iron, and energy in every single meal.',
    
    'bonus.1.title': 'Visual Guide to Complementary Feeding',
    'bonus.2.title': 'Complementary Feeding + Recipes',
    'bonus.3.title': 'Practical Baby Meal Planner – Starting Solids',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('nutribebe-lang') as Language) || 'fr';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('nutribebe-lang', lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("useLanguage must be used within LanguageProvider");
  return context;
};
